[features]
seeds = false
[programs.localnet]
record_anchor = "FGQLqP4smSphjS1WRamE3zEezL8tCFZrsu4Wg5z2Kq4r"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/anurag/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
